### ISSUE TITLE
Include header text consistent with parent design

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-aria-practices#28]
e.g.:
![image](https://user-images.githubusercontent.com/6991814/162531039-22312214-ed08-4d82-9b13-5b2fa1a39118.png)
![image](https://user-images.githubusercontent.com/6991814/162531143-da30ecb8-b0ec-4dfa-b8dc-a3bba7097cdd.png)

## name (ARIA Authoring Practices)

What are pros and cons of "ARIA Authoring Practices" vs "ARIA Authoring Practices Guide"?

## tagline
Brief explanatory phrase with important point (e.g., Supplemental Guidance includes “not required to meet WCAG”, Rules has "For developers of evaluation tools and test methodologies" to clarify that it's probably too much for others)

Consider a short phrase that would:
* provide context for people who land here from a search engine and don't know about ARIA, &/or
* clarify an important point, &/or
* address a common misunderstanding
* provide expansion of "ARIA"

## link to About page = About ARIA Authoring Practices

Note EOWG can help with ideas on 1 and 2 if useful. (@iadawn probably has ideas)

## code

https://wai-website-theme.netlify.app/writing/standalone-resources/#header-name-of-set-of-resources-and-tagline
```
standalone_resource_header:
  title: ARIA Authoring Practices
  subtitle: @@ to be determined @@

standalone_resource_header:
  link:
    ref: /@@/about/
    title: About ARIA Authoring Practices
```
